### ISSUE TITLE
Token transfers in tx details page

### ISSUE THREAD

**Issue by saimeunt** [walnuthq/op-scan#13]
# Token transfers in tx details page

## ⚠️ Reading contributors guidelines to get assigned is MANDATORY!

[Read contributors guidelines](https://github.com/walnuthq/op-scan/issues/1)

## User stories

- As a user, I want to see the list of ERC20 tokens transfers that occurred in a transaction.
For each item in the list, I can click on from / to / token addresses and get redirected to the corresponding account detail page.

## Validation

It should look like the Etherscan token transfers list, eg. https://optimistic.etherscan.io/tx/0x3b680d4727227d6afb35ddf620c3b16e33877f3cc06ec1151a6c45bd167b9f30
For the time being, we will only track ERC20 transfers and display only the token amount and raw addresses from / to / token, you should not compute the amount in $ or try to map the the token address to a list of known tokens.
You do not need to compute the net transfers either.

![Image](https://github.com/walnuthq/op-scan/assets/5597359/827e1db4-c08c-4bd0-8e2a-c00af09249d0)

## Implementation

You will need to leverage the logs emitted in the transaction and create your list of token transfers from the `Transfer` events.
You should continue the work already done on the basic tx detail page and reuse the description list component.

## Resources

- OpenZeppelin ERC20 docs: https://docs.openzeppelin.com/contracts/5.x/erc20

**Comment by melnikga** [comment]
Hi, can I take this?

**Comment by addegbenga** [comment]
will like to work on this here is my [OD hack profile](https://app.onlydust.com/u/addegbenga)

**Comment by Dprof-in-tech** [comment]
Hello @saimeunt 
I am Isaac, a full stack JavaScript developer with a proven record of successful contributions to starknet and of hack projects.

I would love to be assigned to this issue and would be sure to deliver a solution in 2 business days and if there are any blockers I would tender a notice beforehand.

My solution would be to follow the requirements and provide a token transfer page with minimal features as requested.

Take inspiration from the provided link while making sure the user experience is as good as the user interface and deliver in a timely manner.

Below is my Onlydust contribution profile

https://app.onlydust.com/u/Dprof-in-tech

**Comment by saimeunt** [comment]
Assigning to @melnikga as he is a returning contributor.
@Dprof-in-tech Thanks for your interest I will assign to you another similar issue.

**Comment by Dprof-in-tech** [comment]
> Assigning to @melnikga as he is a returning contributor.
> 
> @Dprof-in-tech Thanks for your interest I will assign to you another similar issue. 

Okay ser
