### ISSUE TITLE
Design for a rollup banner for Optimistic Gathering event

### ISSUE THREAD

**Issue by mazurroman** [walnuthq/op-scan#24]
This issue will be assigned to [Kuro Emmanuel ](https://github.com/lamkuro) who provided the best mock of the rollup and won the project. The mock design is attached.

**Requirements:**
* Deadline for the finaldesign: Wednesday 26th June, 2024
* The final PDF file must meet specifications of the print shop we will use to print the rollup. See "Technical info", "Practical info" and "Templates" on the shop's website [here](https://www.h2impression.fr/en/p/rollup-recto?s=1&f=c-rollup-xbanner).
* Format: [85x200cm aluminium template](https://www.h2impression.fr/assets/uploads/Gabarits/GABARIT%20ROLL%20UP%2085x203.pdf)

![walnut rollup 3](https://github.com/walnuthq/op-scan/assets/2983746/95dc206d-7cd3-46e6-bda3-cd05c1f832fd)

**Comment by lamkuro** [comment]
thank you

**Comment by lamkuro** [comment]
[walnut rollup new 1.pdf](https://github.com/user-attachments/files/15991934/walnut.rollup.new.1.pdf)
 issue completed
