### ISSUE TITLE
Initial setup feedback

### ISSUE THREAD

**Issue by mazurroman** [walnuthq/op-scan#3]
- [ ] Fresh install, with no changes done to the project, created a github change file in the pnpm-lock.yaml file, see the following screenshot
![CleanShot 2024-06-17 at 16 35 33@2x](https://github.com/walnuthq/op-scan/assets/2983746/8fde0c91-b3c3-430b-ad29-af134fdd3f2f)

- [ ] small improvement: would be great to use a transparent logo so that there is no white background in the dark version. I am attaching the logo

![opscan-logo-transparent](https://github.com/walnuthq/op-scan/assets/2983746/47e0700e-e933-4307-b52c-9d6a4498b7b0)

**Comment by bhavyagosai** [comment]
Hey, if this is up for contribution, i can take a look at the logo issue. I have cleaned up/made logos in the past, example for simpleicons

**Comment by saimeunt** [comment]
@mazurroman Logo has been updated accordingly in #4 
Concerning the `pnpm-lock.yaml` inconsistencies, this may have to do with an outdated pnpm version on your end? (see https://github.com/pnpm/pnpm/issues/7934).
Maybe we can update the README to specify a recommended version of pnpm >= 9 to avoid this problem in upcoming PRs, wdyt?

**Comment by jaipaljadeja** [comment]
> @mazurroman Logo has been updated accordingly in #4 Concerning the `pnpm-lock.yaml` inconsistencies, this may have to do with an outdated pnpm version on your end? (see [pnpm/pnpm#7934](https://github.com/pnpm/pnpm/issues/7934)). Maybe we can update the README to specify a recommended version of pnpm >= 9 to avoid this problem in upcoming PRs, wdyt?

Yes! you are correct the inconsistencies comes because of different pnpm versions.
To solve this problem you can mention the version of package manager in `package.json`

For example: 
```
....
"packageManager": "pnpm@8.5.1"
...
```

Also you can add in README that people should enable `corepack`  in Node and install `pnpm` using `corepack` ([guide](https://pnpm.io/installation#using-corepack))

Next time whenever you will use pnpm in any project with `packageManager` present in `package.json`, Node will automatically install the required pnpm version (if not installed) and use it for the same project.

**Comment by od-hunter** [comment]
Can I be assigned to update the README please?

**Comment by Jemiiah** [comment]
@od-hunter chill can you do the issue 😪

**Comment by od-hunter** [comment]
@Jemiiah focus on you bro

**Comment by saimeunt** [comment]
@jaipaljadeja Thanks for your comment, I didn't know about `corepack` and just found out, it's looking promising!
While it's probably the way to go in the foreseeable future, `corepack` is still experimental and I want to keep the tech stack aligned with OP Stack so I don't want to introduce another requirement and I prefer to wait until broader adoption.
Closing as pnpm >= 9 was added in the README.
