### ISSUE TITLE
UI: Consolidate table views

### ISSUE THREAD

**Issue by mazurroman** [walnuthq/op-scan#46]
## ⚠️ **Reading contributors guidelines to get assigned is MANDATORY!**
[Read contributor guidelines](https://github.com/walnuthq/op-scan/issues/1)

## Description
This issue is about the following pages:
* https://opscan.co/blocks
* https://opscan.co/txs
* https://opscan.co/txs-enqueued

## TODO on the Blocks page
[This page](https://opscan.co/blocks).

* Align the "Total of ..." section, and the "Latest block number:[123330938]" section with the table content (push it to the left)
* Use bold
* Make it look more like on the original ([link](https://optimistic.etherscan.io/blocks))

## TODO on the `/txs` and `/txs-enqueued` pages

* Those pages should be more consistent with the /blocks page. Currently, the headings are different. The table widths are also different. It should all be consistent + all pages should also have pagination.
* Use https://optimistic.etherscan.io/ as a reference

**Comment by Iwueseiter** [comment]
Hi @mazurroman can I work on this?
I’m a frontend developer and also a blockchain developer and I’ve contributed to onlydust projects.
I would make sure all the pages have a consistent UI and other requirements also met. I’d make sure the PR meet the requirements specified.
I’d deliver a PR promptly.

**Comment by melnikga** [comment]
I can take this

**Comment by PoulavBhowmick03** [comment]
Gm, I would love to contribute and fix this issue
I am a fullstack developer, I am quite familiar with the repository and can make the UI seemless, similar to the blocks page and make the changes that have been asked
Would love to workon this issue!

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/opscan).

### My background and how it can be leveraged
my name is  nuelo  a frontend  develop

### How I plan on tackling this issue
1.Align the Sections and Use Bold
To ensure that "Total of ..." section and  "Latest block number:[123330938]" section are aligned with the table content and use bold formatting.

2. Make Headings Consistent

3. Make Table Widths Consistent
Ensure the table widths are the same across all pages.

4. Add Pagination
Ensure all pages have pagination.

5. Reference Optimistic Etherscan
Use https://optimistic.etherscan.io/ as a reference for design consistency.
- Inspect the layout and styles used on Optimistic Etherscan.
- Adjust your styles and HTML to match the look and feel.

**Comment by MariangelaNM** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/opscan).

### My background and how it can be leveraged
Hello, I'm Mariangela. I'm a software developer specializing in front-end development, and I would like to work on this project.

### How I plan on tackling this issue

### Review the Design of the `/blocks` Page:

1. **Headings:**
   I will analyze the headings on the `/blocks` page and compare them with those on other pages. I will ensure that all headings follow the same format and style.

2. **Table Widths:**
   I will check the table widths on `/blocks` and make sure other pages use the same widths. This may involve adjusting the CSS to ensure the tables are properly aligned.

3. **Pagination:**
   I will implement a pagination system similar to that on the `/blocks` page on all pages that require it.

### Implement Pagination:

1. If there is no pagination on other pages yet, I can use a pagination component already implemented on `/blocks` or create a new one if necessary.
2. I will ensure that the pagination is consistent in terms of style and functionality.

### Reference Etherscan Optimism:

1. I will use [Etherscan Optimism](https://optimistic.etherscan.io/) as a reference to ensure that the tables, headings, and pagination are consistent and well-designed.
2. I will review how they handle pagination and table design and try to replicate that approach in application.

**Comment by saimeunt** [comment]
This issue is not planned at the moment but we might reopen it later, sorry for the confusion.

**Comment by ShantelPeters** [comment]
I am applying to this issue via https://app.onlydust.com/p/opscan

Hello, I've read the contributors guidelines and I'm excited to help with this task. I understand the requirements:

1. Update the Blocks page:
    - Align the "Total of ..." and "Latest block number:[123330938]" sections with the table content.
    - Use bold text for these sections.
    - Make the design consistent with the reference page ((link unavailable)).
2. Update the /txs and /txs-enqueued pages:
    - Make the headings consistent with the Blocks page.
    - Align the table widths with the Blocks page.
    - Add pagination to all pages (/blocks, /txs, and /txs-enqueued).

To achieve this, I would:

1. Inspect the HTML and CSS of the pages to identify the necessary changes.
2. Update the CSS to align the sections and tables, and add bold text where required.
3. Ensure consistency across all pages (/blocks, /txs, and /txs-enqueued).
4. Add pagination to each page, following the design of the reference page.

Please assign me this task, and I'll deliver the updated code to achieve the desired design consistency and pagination.
